### ISSUE TITLE
12.1 Look at adding an extra screenshot

### ISSUE THREAD

**Issue by LibbyBrookes** [mattparker/lamplighthelp#103]
At the bottom of the second scren view, so referring text makes sense (Profile name search, date profile created, visibility current or archived).

Also 'Profile name search' isn't mentioned in the text.

**Comment by LibbyBrookes** [comment]
Before the text 'next option' provide a screenshot of the lower half of that page in LL as it doesn't make sense with just the top half shown here.

**Comment by ClareParker** [comment]
updated text and inserted new image 12.1.0c
