### ISSUE TITLE
16.4 Make search bar in work records tab a personal setting, not a global one

### ISSUE THREAD

**Issue by SamRimmer17** [mattparker/lamplighthelp#118]
Make search bar in work records a personal setting, not a global one.

**Comment by LibbyBrookes** [comment]
This needs changing
![image](https://user-images.githubusercontent.com/23317623/118837507-cb5a7e80-b8bc-11eb-81b4-aa2b2a3ab644.png). You can now decide in 'personal settings' whether or not you want a filter bar above activities tables in profiles. This options appears in 'profile settings' - will need adding to page 16.4.2. We also need a note on 'Global settings' page 16.12.4 that although it can be set here, you can override it in personal settings.
