### ISSUE TITLE
Change of labels in outcome reports page 14.4.1

### ISSUE THREAD

**Issue by mattparker** [mattparker/lamplighthelp#126]
We've changed labels to 'increased scores' and 'decreased scores' in outcomes reports and need to update bullet points to reflect that in manual.

ref. https://github.com/mattparker/lamplight/issues/7656

https://github.com/mattparker/lamplighthelp/blob/main/source/14-4-1_Outcome_Reports_-_Data_Produced_When_Looking_at_Change.markdown

**Comment by ClareParker** [comment]
uploaded new images 14.4.1a and 14.4.1b and updated language
