### ISSUE TITLE
13.1 - Ctrl-click many tickboxes

### ISSUE THREAD

**Issue by ClareParker** [mattparker/lamplighthelp#173]
Ctrl-click many tickboxes

**Comment by ClaireMGitHub** [comment]
Use the video in https://mailchi.mp/lamplightdb/training-with-lamplight-15613132
Summer newsletter 2023
HOW TO MAKE THIS ANSWER MORE EASILY SEARCHABLE?

Reference is included in 12.1.1 referencing Ward and Borough
 You can select more than one ward or borough from each list. To do this, hold down the Ctrl button on your keyboard while you click on the options that you want, e.g. Chichester and Chiltern. To deselect an option, Ctrl click again

EDIT 13.1
Relationships. You can show information in your data view about named individuals/organisations that members of the list are linked to. Click to select the relationship type you wish to use, and whether you want to see the 'name only' of the linked profile, or 'name and contact details'. **To select more than one type of relationship hold down the Ctrl button on your keyboard while you click on the options that you want, e.g. Spouse and Children. To deselect an option, Ctrl click again.** If you select 'name and contact details for download' you will get the same information as 'name and contact details' but each field is separated by a pipe symbol - | - and empty fields are included. This means that if you download the data and do 'text to columns' you'll be able to get the data nicely. However it doesn't look so nice on screen if you just want to see the information in Lamplight.

**Comment by ClareParker** [comment]
Commit to 13.1 done
