### ISSUE TITLE
12.2 - update about manual lists

### ISSUE THREAD

**Issue by ClareParker** [mattparker/lamplighthelp#183]
alter heading and include How to add and remove a profile from a manual group

**Comment by ClaireMGitHub** [comment]
Screen shot is incorrect for Group members

List Members Tab
...
To remove someone from the list, click the red cross in the right-hand column of the table _**and the name will be removed**_

NEW
Deleting Members from a manual list
Edit the manual list and go to the group members tab.  To remove someone from the list, click the red cross in the right-hand column of the table and save your changes.  You will notice that the List size in the lists table has reduced.

**Comment by ClareParker** [comment]
New image for adding/removing members of a list 11.2.0d
Updated text used
Included link to 'editing groups'
