### ISSUE TITLE
Output from diagnostics - 19/03/19

### ISSUE THREAD

**Issue by mattparker** [mattparker/lamplighthelp#41]
Hope this might be helpful: this is what the new diagnostics mode generates as of now (ignore the ones that say 'Problem looking at page .'

Errors while building help files:
Translations: Page 16.7.3 contains "{{groups}}".
Translations: Page 16.7.3 contains "{{groups}}".
Translations: Page 16.7.3 contains "{{groups}}".
Translations: Page 16.7.3 contains "{{group dataview}}".
Translations: Page 16.7.3 contains "{{group dataview}}".
Translations: Page 16.7.3 contains "{{outcomes}}".
Translations: Page 16.7.3 contains "{{outcomes}}".
Translations: Page 16.7.3 contains "{{groups}}".
Translations: Page 16.7.3 contains "{{group dataview}}".
Faulty link: Page 9.1.2 not found in page 10.1.2.
Faulty link: Page 18.2.3 not found in page 10.1.2.
Translations: Page 16.13.1 contains "{{service user}}".
Translations: Page 16.13.1 contains "{{service user}}".
Translations: Page 16.13.1 contains "{{group data view}}".
Translations: Page 16.13.1 contains "{{group data view}}".
Translations: Page 13 contains "{{reports}}".
Translations: Page 13 contains "{{reports}}".
Translations: Page 13 contains "{{reports}}".
Translations: Page 13 contains "{{reports}}".
Translations: Page 13 contains "{{manager}}".
Translations: Page 13 contains "{{system administrator}}".
Translations: Page 13 contains "{{reporting}}".
Translations: Page 13 contains "{{reports}}".
Translations: Page 13 contains "{{reports}}".
Translations: Page 13 contains "{{matching}}".
Translations: Page 16.9 contains "{{rereferral}}".
Translations: Page 16.9 contains "{{outcomes}}".
Translations: Page 16.9 contains "{{reports}}".
Translations: Page 16.12.1 contains "{{service user}}".
Faulty link: Page 24.6.1 not found in page 17.2.
Faulty link: Page 24.6.2 not found in page 17.2.
Faulty link: Page 24.6.3 not found in page 17.2.
Translations: Page 16.12 contains "{{cases}}".
Translations: Page 16.12 contains "{{case}}".
Faulty image: file 25b.png not found, used in page 3.9.
Faulty image: file 21a.png not found, used in page 3.8.1.
Faulty image: file 21b.png not found, used in page 3.8.1.
Faulty link: Page 18.2 not found in page 7.1.2.
Faulty link: Page 18.8 not found in page 10.1.5.
Faulty link: Page 9.2.10 not found in page 10.1.5.
Faulty link: Page 26.2.1 not found in page 20.2.5.
Translations: Page 17.2.3 contains "{{projects}}".
Translations: Page 17.2.3 contains "{{projects}}".
Translations: Page 17.2.3 contains "{{projects}}".
Problem looking at page .
Faulty image: file 259a.png not found, used in page 20.6.3.
Faulty link: Page 26.6.1 not found in page 20.6.3.
Translations: Page 12.2 contains "{{group data views}}".
Faulty link: Page 18.3 not found in page 28.2.
Translations: Page 28.2 contains "{{families}}".
Translations: Page 28.2 contains "{{families}}".
Translations: Page 28.2 contains "{{projects}}".
Translations: Page 28.2 contains "{{projects}}".
Faulty link: Page 26.6.2 not found in page 20.7.1.
Faulty link: Page 24.6 not found in page 17.
Faulty image: file 249a.png not found, used in page 20.2.8.
Faulty link: Page 26.2.1 not found in page 20.2.8.
Faulty link: Page 18.6.2 not found in page 16.5.2.
Faulty link: Page 18.4 not found in page 7.1.
Faulty link: Page 9.1.1 not found in page 7.1.
Faulty link: Page 9.1.2 not found in page 7.1.
Faulty link: Page 9.1.4 not found in page 7.1.
Faulty link: Page 14.8.1 not found in page 16.4.
Faulty link: Page 17.1.1 not found in page 24.5.
Faulty link: Page 14.8.1 not found in page 12.2.4.
Faulty link: Page 15 not found in page 23.2.
Faulty link: Page 9.1.2 not found in page 23.2.
Faulty link: Page 15 not found in page 23.2.
Translations: Page 23.2 contains "{{eval data}}".
Problem looking at page .
Translations: Page 9.2 contains "{{case}}".
Translations: Page 16.8.2 contains "{{groups}}".
Faulty link: Page 18.2 not found in page 16.6.1.
Translations: Page 16.6.1 contains "{{grsoup}}".
Translations: Page 16.6.1 contains "{{workareas}}".
Translations: Page 16.6.1 contains "{{workareas}}".
Translations: Page 16.6.1 contains "{{workareas}}".
Translations: Page 13.1.1 contains "{{relationship}}".
Faulty link: Page 17.1.2 not found in page 14.5.
Faulty link: Page 9.2.2 not found in page 28.3.2.
Faulty image: file 234a.png not found, used in page 17.2.4.
Faulty image: file 234b.png not found, used in page 17.2.4.
Translations: Page 8.2 contains "{{link case}}".
Translations: Page 8.2 contains "{{outcomes}}".
Faulty link: Page 17.3.1 not found in page 13.4.3.
Faulty image: file 107a.png not found, used in page 11.6.
Faulty link: Page 9.1.2 not found in page 11.
Faulty link: Page 17.1.1 not found in page 11.
Problem looking at page .
Translations: Page 9.9 contains "{{linked cases}}".
Translations: Page 16.12.2 contains "{{evaluation}}".
Translations: Page 16.12.2 contains "{{evaluation}}".
Translations: Page 16.12.2 contains "{{evaluation}}".
Translations: Page 16.12.2 contains "{{evaluation}}".
Translations: Page 16.12.2 contains "{{evaluation}}".
Translations: Page 16.12.2 contains "{{evaluation}}".
Translations: Page 16.12.2 contains "{{evaluation}}".
Translations: Page 16.12.2 contains "{{evaluation}}".
Translations: Page 16.12.2 contains "{{evaluation}}".
Translations: Page 16.12.2 contains "{{evaluation}}".
Faulty link: Page 17.5 not found in page 23.6.
Faulty link: Page 17.1.4 not found in page 23.6.
Faulty image: file 1222.png not found, used in page 20.
Problem looking at page .
Faulty link: Page 18.3 not found in page 5.5.
Faulty link: Page 17.51 not found in page 23.3.
Faulty link: Page 17.51 not found in page 23.3.
Faulty link: Page 14.8.2 not found in page 12.3.
Faulty link: Page 17.1.1 not found in page 13.1.3.
Translations: Page 13.1.3 contains "{{groups}}".
Faulty image: file 227a.png not found, used in page 30.1.
Translations: Page 30.1 contains "{{waiting lists}}".
Translations: Page 30.1 contains "{{subworkareas}}".
Translations: Page 30.1 contains "{{subworkareas}}".
Translations: Page 30.1 contains "{{service user referred}}".
Translations: Page 30.1 contains "{{projects}}".
Faulty image: file 225a.png not found, used in page 21.2.1.
Problem looking at page .
Faulty image: file 252a.png not found, used in page 20.4.1.
Faulty image: file 42a.png not found, used in page 5.8.
Translations: Page 29.1.1 contains "{{staff profiles}}".
Faulty link: Page 8.7 not found in page 13.3.
Faulty image: file 243a.png not found, used in page 20.2.3.
Faulty link: Page 26.2.1 not found in page 20.2.3.
Faulty link: Page 26.2.5 not found in page 20.2.3.
Faulty link: Page 15 not found in page 8.
Faulty image: file 229a.png not found, used in page 30.2.
Faulty link: Page 14.8 not found in page 30.2.
Translations: Page 30.2 contains "{{lampglight}}".
Faulty image: file 257a.png not found, used in page 20.6.1.
Faulty image: file 257b.png not found, used in page 20.6.1.
Faulty link: Page 26.6.2 not found in page 20.6.1.
Faulty link: Page 26.7.1 not found in page 20.6.1.
Faulty link: Page 26.7.2 not found in page 20.6.1.
Faulty link: Page 26.7.1 not found in page 20.6.1.
Faulty link: Page 26.7.2 not found in page 20.6.1.
Faulty link: Page 26.6.2 not found in page 20.6.1.
Faulty image: file 117b.png not found, used in page 22.2.
Faulty link: Page 9.1.1 not found in page 22.2.
Faulty link: Page 9.1.2 not found in page 22.2.
Translations: Page 16.12.4 contains "{{service user}}".
Translations: Page 16.12.4 contains "{{outcomes}}".
Translations: Page 16.12.4 contains "{{referrals}}".
Translations: Page 16.12.4 contains "{{evaluation}}".
Faulty image: file 4a.png not found, used in page 5.1.
Faulty link: Page 18.3 not found in page 5.1.
Faulty link: Page 11.1.2 not found in page 8.1.
Faulty link: Page 18.4 not found in page 8.1.
Translations: Page 25 contains "{{reports}}".
Faulty image: file 256a.png not found, used in page 20.6.
Faulty image: file 256b.png not found, used in page 20.6.
Faulty link: Page 26.2 not found in page 20.6.
Faulty link: Page 26.6.1 not found in page 20.6.
Faulty link: Page 26.6.2 not found in page 20.6.
Faulty link: Page 8.7 not found in page 13.5.
Translations: Page 13.5 contains "{{reports}}".
Faulty link: Page 8.6 not found in page 4.2.
Faulty link: Page 18.12 not found in page 4.2.
Faulty link: Page 18.2.1 not found in page 16.6.2.
Translations: Page 9.1 contains "{{linked Case}}".
Faulty image: file 221a.png not found, used in page 30.4.
Faulty image: file 221b.png not found, used in page 30.4.
Translations: Page 16.7.1 contains "{{groups}}".
Translations: Page 16.7.1 contains "{{group dataview}}".
Translations: Page 16.7.1 contains "{{groups}}".
Translations: Page 16.7.1 contains "{{group data views}}".
Translations: Page 16.10 contains "{{outcomes}}".
Translations: Page 16.10 contains "{{referrals}}".
Faulty image: file 106a.png not found, used in page 11.5.
Problem looking at page .
Translations: Page 11.5 contains "{{group data view}}".
Translations: Page 11.5 contains "{{group data views}}".
Translations: Page 16.4.1 contains "{{users}}".
Translations: Page 16.4.1 contains "{{case}}".
Translations: Page 16.4.1 contains "{{case}}".
Translations: Page 16.4.1 contains "{{case}}".
Translations: Page 16.4.1 contains "{{case}}".
Translations: Page 16.4.1 contains "{{outcomes}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{workareas}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Translations: Page 16.12.3 contains "{{case}}".
Faulty image: file 255a.png not found, used in page 20.5.
Faulty image: file 255b.png not found, used in page 20.5.
Translations: Page 14 contains "{{matching}}".
Translations: Page 11.1.1 contains "{{work area}}".
Translations: Page 21.1.1 contains "{{first name}}".
Translations: Page 21.1.1 contains "{{first name}}".
Faulty link: Page 4.9 not found in page 24.2.
Translations: Page 27.2.1 contains "{{lampglight}}".
Faulty link: Page 4.3.5 not found in page 3.5.3.
Faulty image: file 104b.png not found, used in page 11.2.
Translations: Page 16.7.2 contains "{{group data views}}".
Faulty link: Page 4.4.1 not found in page 3.7.
Translations: Page 3.3 contains "{{activites}}".
Faulty link: Page 18.12 not found in page 4.1.
Translations: Page 16.4.2 contains "{{outcomes}}".
Translations: Page 16.4.2 contains "{{outcomes}}".
Translations: Page 16.4.2 contains "{{work area}}".
Faulty image: file 258a.png not found, used in page 20.6.2.
Faulty link: Page 26.7.1 not found in page 20.6.2.
Faulty link: Page 26.7.2 not found in page 20.6.2.
Faulty link: Page 17.6.1 not found in page 14.1.2.
Translations: Page 7.1.1 contains "{{work area}}".
Translations: Page 5.6.1 contains "{{groups}}".
Translations: Page 11.1 contains "{{groups}}".
Translations: Page 11.1 contains "{{groups}}".
Translations: Page 11.1 contains "{{groups}}".
Translations: Page 11.1 contains "{{cases}}".
Faulty link: Page 14.8 not found in page 11.8.
Faulty image: file 254a.png not found, used in page 20.4.3.
Translations: Page 10 contains "{{comms}}".
Problem looking at page .
Problem looking at page .
Faulty link: Page 14.8.2 not found in page 12.
Faulty image: file 230a.png not found, used in page 30.3.
Faulty image: file 242a.png not found, used in page 20.2.2.
Translations: Page 5.6 contains "{{orgs}}".
Translations: Page 16.7.5 contains "{{attendance}}".
Faulty image: file 253a.png not found, used in page 20.4.2.
Faulty image: file 248a.png not found, used in page 20.2.7.
Faulty image: file 248b.png not found, used in page 20.2.7.
Faulty link: Page 26.2.1 not found in page 20.2.7.
Faulty image: file 245a.png not found, used in page 20.2.4.
Faulty link: Page 26.2.1 not found in page 20.2.4.
Faulty link: Page 26.2.5 not found in page 20.2.4.
Faulty link: Page 18.2 not found in page 6.1.2.
Translations: Page 16 contains "{{case}}".
Faulty link: Page 18.12 not found in page 4.
Faulty link: Page 26.1.1 not found in page 20.4.
Faulty link: Page 26.5 not found in page 20.4.
Faulty image: file 235a.png not found, used in page 17.2.2.
Faulty image: file 235b.png not found, used in page 17.2.2.
Faulty image: file 250a.png not found, used in page 20.3.
Faulty link: Page 26.2 not found in page 20.3.
Faulty link: Page 26.2.1 not found in page 20.3.
Faulty image: file 247a.png not found, used in page 20.2.6.
Faulty link: Page 26.2.1 not found in page 20.2.6.
Faulty image: file 77b.png not found, used in page 8.1.3.
Faulty link: Page 18.2 not found in page 8.1.2.

**Comment by LibbyBrookes** [comment]
Done
