### ISSUE TITLE
Image 210a.png is broken

### ISSUE THREAD

**Issue by mattparker** [mattparker/lamplighthelp#56]
It's there but doesn't load (afraid I've no idea why) - a few of the others in that range also appear to be broken.  let me know if I can help with these...

**Comment by mattparker** [comment]
202a
203a.jpg (tho 203a.png is OK, I don't think it's the correct image)

**Comment by mattparker** [comment]
210a is in 23.3.0
202a is in 24.2.0
203a.jpg 24.3.0

**Comment by mattparker** [comment]
219a =>16.7.4 and 7.1.5
217a => (unused)
209a => 8.1.2
208a => (unused)
207a => (unused)

**Comment by LibbyBrookes** [comment]
Done. Though when you were looking at it you could see 203a, when I came to it there was text rather than an image.
