### ISSUE TITLE
Latest diagnostics

### ISSUE THREAD

**Issue by mattparker** [mattparker/lamplighthelp#58]
(some are mine, sorry!)

Faulty image: file 16.12.3b.png not found, used in page 16.12.3.
Faulty image: file 16.12.3c.png not found, used in page 16.12.3.
Faulty image: file 16.12.3d.png not found, used in page 16.12.3.
Faulty image: file 16.12.3e.png not found, used in page 16.12.3.
Faulty image: file 16.12.3f.png not found, used in page 16.12.3.
Problem looking at page .
Problem looking at page .
Problem looking at page .
Problem looking at page .
Problem looking at page .
Problem looking at page .
Problem looking at page .
Faulty image: file 26.4.1a.PNG not found, used in page 26.4.
Translations: Page 14 contains "{{volunteer opportunity}}".
Translations: Page 14 contains "{{volunteer application}}".
Faulty image: file 12.3.0a.png not found, used in page 12.3.
Faulty link: Page 12.2.3 not found in page 16.4.1.
Problem looking at page .
Translations: Page 21.2.2 contains "{{list}}".
Problem looking at page .

**Comment by LibbyBrookes** [comment]
Done
