### ISSUE TITLE
Link in 26-5-1 to API links doesn't work

### ISSUE THREAD

**Issue by LibbyBrookes** [mattparker/lamplighthelp#62]
Requests should be made to `https://lamplight.online/api/volunteering/opportunity`.
You will need to add a `key` parameter, with the API key.

**Comment by LibbyBrookes** [comment]
Hi Matt Is the link in this page one that needs to work, or is it just for demo purposes? Thanks

**Comment by mattparker** [comment]
No it's not supposed to work, it's for information that that's the link. It won't work as is.
