### ISSUE TITLE
8.1.4 Outcomes have 'respondent' tab not 'attendee'

### ISSUE THREAD

**Issue by LibbyBrookes** [mattparker/lamplighthelp#98]
Change reference to 'respondent'.

**Comment by LibbyBrookes** [comment]
Towards the bottom of the page there are a couple of references after the final picture

**Comment by mattparker** [comment]
Couldn't see references after the final picture - perhaps double check other nearby pages in the manual too?

**Comment by ClareParker** [comment]
can't see reference, appears to have been updated with simple search already
